In [1]:
import numpy as np

In [3]:
def parse(content):
    _id , f1 , f2, f3 , a , time , p = content.split(",")
    a = list(a)
    p = int(p)
    a = [int(i) for i in a]
    a = np.array(a)
    a = np.reshape(a,(8,8))
    print(_id)
    print(f1)
    print(f2)
    print(f3)
    print(a)
    print(time)
    print(p)
    

In [4]:
parse("10000006,21,2,12,0000000000000000001100001111000111110001101000110000011100000011,10-12-20-51-7,1")

10000006
21
2
12
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 1 1 0 0 0 0]
 [1 1 1 1 0 0 0 1]
 [1 1 1 1 0 0 0 1]
 [1 0 1 0 0 0 1 1]
 [0 0 0 0 0 1 1 1]
 [0 0 0 0 0 0 1 1]]
10-12-20-51-7
1
